### ISSUE TITLE
Сообщение о прибытии шаттла во время его отправки

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#111]
Во время отстыковки шаттла со станции, всем приходит оповещение о том что шаттл не отстыковывается, а наоборот возвращается. Тестировалось с Калипсо и Гаппи
![default](https://cloud.githubusercontent.com/assets/18286472/24828426/5ef3bf2c-1c76-11e7-832d-591aeccb81e2.png)

**Comment by ghost** [comment]
This is not tg issue
