### ISSUE TITLE
Локация Некрополис

### ISSUE THREAD

**Issue by bear1ake** [infinitystation/-tg-station#22]
- [ ] Разработать план локации и выложить сюда. Учесть то, что локация будет замещать нынешнюю бан-тюрьму:
- [ ] Реализовать план;
- [ ] Включить в список карт вместо z9.dmm (Бан-тюрьма).

**Comment by Terror4000rus** [comment]
Начал разработку - начало карты уже готово и есть в билде.
Конкретного плана нет, но есть в идеях нечто вроде подземелья.

**Comment by Terror4000rus** [comment]
Выпилил некоторые теги.
Первый - так-как карту делаю я один.
Второй - скрипя сердцем и собрав силу воли в кулак, таки делаю.
Третий - one man army :D
