### ISSUE TITLE
Финансовая система

### ISSUE THREAD

**Issue by bear1ake** [infinitystation/-tg-station#23]
- [x] Разработать алгоритм финансовой системы;
- [ ] Реализовать алгоритм;
- [ ] Включить в билд.

**Comment by dexofan23** [comment]
Что оно должна в себя включать? Система как на бэе с банкоматами и кассами как на гунах?

**Comment by ghost** [comment]
Есть несколько идей относительно этого, на вашем сервере вполне бы смотрелось:
0)СМЕРТЕЛЬНЫЙ ГОЛОД
1)обрезать людям стартовый капитал (например, личные средства на карте покрамсать значительно, счета отделов оставить как есть/незначительно порезать)
2)вызов каргошаттла делать на за каргопоинты а за деньги отделов (отдел, который ничего не производит, ничего себе и не закажет)
3)дать больше власти над балансом ХоПу, дать ему возможность перечислять все деньги отделов, например. Дать остальным главам возможность управлять балансом своего департамента и перечислять деньги работникам (станция может умереть от голода из-за хопа-мудака который захапал себе все средства )
4)Упростить сервисным профам учет покупок и продаж, например поставить в бар, на кухню считыватель карт, который будет снимать сумму за сделанный барменом/поваром товар
(я не знаю как касса работает на гунах)
5)Доделать модуль с задачами профессий, что должно стать основным источником дохода (там только 3 задачи на научный отдел)

**Comment by ghost** [comment]
Надеюсь, вы это уже читали:
https://github.com/d3athrow/vgstation13/issues/3856
https://github.com/d3athrow/vgstation13/issues/6020

**Comment by ghost** [comment]
Привет Русский Комрад! Я думаю "Финансовая система" oтлично идеи!
