### ISSUE TITLE
Некорректно работает шокер СМО

### ISSUE THREAD

**Issue by Pizhik** [infinitystation/-tg-station#30]
Некорректно работает шокер СМО. Вставляю батарейку, при examine по шокеру пишет:
  That's a shocker.
Zap-zap!
It is a small item.
The baton is 100% charged.
При попытке включить:
The shocker is out of charge.
Бью, например, по себе:
****\* ****\* has prodded you with the shocker. Luckily it was off

**Comment by ghost** [comment]
Во первых, не знаю какою именно батарейку ты вставил, поэтому узнать суть проблемы не могу, ибо шокер по коду наследник станнбатона, с небольшой правкой кода proc'а.
Второе: 
- ****\* ****\* has prodded you with the shocker. Luckily it was off 

Это фича, шанс блокировки так сказать.
- The baton is 100% charged.

Да, об этом я знаю, но чинить это лень, банально лень ибо в силу механа эта надпись ничего не делает.

Сейчас я только-что зашёл на сервер и протестировал шокер, он работает.
Через некоторое время сделаю абдейт на замену шокеров уже с вставленной батарейкой.

**Comment by Pizhik** [comment]
Батарейка из автолата.

**Comment by ghost** [comment]
Дело в том, что данная батарейка (самая белая, без красных полосок) не подходит для станнбатонов, она по каким-то причинам то-ли мало-ёмкая и поэтому не подлежит использованию.

Я советую использовать батарейки типа high-capacity или выше.

**Comment by ghost** [comment]
Насчёт сообщения "уколнения", возможно ты просто его не включил, поэтому оно и высвечивается.

**Comment by Pizhik** [comment]
В том-то и дело, что пишет о том что шокер заряжен, а включать - не включается.
Пусть хоть не пишет что заряжен.

**Comment by ghost** [comment]
От того и говорю тебе: это не моя ошибка, тут-то я поделать ничего не могу - явно проблема с энергоёмкостью батарейки и поэтому она не пригодна для использования, только класс выше.

Конечно, можно уменьшить энерго-потребление, но иначе этот предмет будет более имбовым в количество использования чем обычная дубинка.

P.s: Вообще можно редактировать, но от этого могут быть лишние конфликты в далёком будущем.

**Comment by ghost** [comment]
Максимум, что я могу сделать, так это поменять описание шокера для предупреждения, а так же сменить текст с baton на shocker.

Я попробую попросить других людей помочь, а пока начинаю работу.

**Comment by ghost** [comment]
Итак, я сделал так чтобы шокеру не подходила белая батарейка.
Теперь же, при загруженной батарейке (которая скоро будет вставлена изначально в шкафу) вместо 10 ударов током можно сделать 8.
По всем другим вопросам я дал ответ и думаю что пора уже закрывать это.

Спасибо за отзыв @Pizhik.
