### ISSUE TITLE
Переквалификация геныча (трансформ)

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#34]
После трансформации генокрада (функция "transform", цена - 5... "очков геныча") нельзя снять медицинскую маску с морды гуманоида. Например, чтобы покушать.
![12451312](https://cloud.githubusercontent.com/assets/18286472/17135550/c6f3e846-5349-11e6-80bb-452fcb5182cd.png)

**Comment by ghost** [comment]
Фича же :D 
Надо тырить гены путём раздевания жертвы и потом превращятся в неё, ибо тогда ты можешь одевать одежду (а сейчас ты её не мог снять, ибо одежда - часть твоей маскировки)
