### ISSUE TITLE
Papercutter

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#35]
В библиотеке есть такая штука, Papercutter. Берешь в одну руку, бумажку (пустую) в другую. Кликаешь бумажкой по пайперкуттеру в руке, куттер заменяется иконкой бумажки. Жмешь на бумажку - она типа разрезается и.. всё. и куттер уже без иконки, просто невидимая фигня.

**Comment by Broda1** [comment]
Зафикшено.
https://github.com/infinitystation/-tg-station/pull/50
