### ISSUE TITLE
Здоровый восьмичасовой сон

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#36]
Хотелось бы видеть возможность "контроля" сна, или по будильнику :D На том же ПДА. :alarm_clock: 
Нажатие на Sleep вводит в сон, повторное - просыпаешься. А не по "таймеру", клацнул спать и всё, и на минуту. Чтобы там отойти можно было, залипнуть где нибудь. Чтобы самому выбирать когда просыпаться.

**Comment by ghost** [comment]
Разберусь. Когда будет сделано - не могу точно сказать.
UPD: Не смогу, простите.

**Comment by Terror4000rus** [comment]
Я не считаю, что это требуется.
Так или иначе, смена длится не более пяти часов - человеку нужен, как максимум, отдых.

**Comment by ghost** [comment]
Закрыто, фича не нужна и достаточно лечь в дормах и написать через /me храпит и пытается дотянуться во сне до чего-то.
