### ISSUE TITLE
Floor tile

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#38]
This is some floor tile
This object does not contain sufficient amounts of metal or glass to be accepted by the autolathe.

Металлические плитки пола не содержат металла? Это новость

**Comment by Terror4000rus** [comment]
Для создание одного пласта металла нужно 4 плитки пола.

**Comment by HetNeSS** [comment]
Да, но в автолат они не суются. Ни в тот который в карго, ни в тот у входа в РнД.

**Comment by ghost** [comment]
origin_tech пойди не выставлен.
