### ISSUE TITLE
Bubblegum

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#42]
После убийства шахтера монстрами-боссами вещи шахтера (рюкзак, пояс и пр.) пропадают.
![2016-08-15 15 31 17](https://cloud.githubusercontent.com/assets/18286472/17662204/5f0fcd62-62fd-11e6-97fc-3050081387b6.png)

**Comment by ghost** [comment]
При любом гибе игрока пропадают вещи с него :\

**Comment by Terror4000rus** [comment]
Так и должно быть - считай, что это кара за то, что шахтер переоценил свои силы.
Плюс этот лут часто девать некуда.
