### ISSUE TITLE
Щит-рука генокрада

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#46]
Щит-рука генокрада не рвет наручники из кабелей. Возможно, меч тоже.

### Комментарий от Quardbreak: 
- [ ] Добавить возможность разрывать наручники из кабелей с помощью острых предметов.

**Comment by Terror4000rus** [comment]
И не должны. Это щит, а не лезвие.
Меч... Хм... Было бы неплохо закодить, чтобы при активном мече рвал.

**Comment by ghost** [comment]
Меняю название темы на реквест фичи.
