### ISSUE TITLE
[Тритор] Chameleon Pack

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#52]
Комплект хамелеона не работал в последней смене, перед падением сервера. При попытке нажать на иконку вещи вверху экрана, это ни к чему не приводило. Надевал костюм, снимал обратно, безрезультатно. То же самое и с остальными вещами (тестил хамелеон-перчатки и хамелеон-бутсы)

**Comment by HetNeSS** [comment]
14:59, 29.08.16

**Comment by Terror4000rus** [comment]
Странно... ТГшники что-то писали про фикс хамелеонского кита.
https://github.com/tgstation/tgstation/pull/20043 - таки да, ожидай обновления.
