### ISSUE TITLE
Не работает взлом шкафчика мультиметом, в любом режиме.

### ISSUE THREAD

**Issue by MAAATRIX2** [infinitystation/-tg-station#56]

**Comment by HetNeSS** [comment]
Равно как и сейфа с кейсом с замочным механизмом) Помню, шмотки свои в кейсе во время ганги хранил, "Вся королевская конница, вся королевская рать.. шалтая-болтая, болтая-шалтая никак не могли разобрать".

**Comment by bear1ake** [comment]
Исправлено
