### ISSUE TITLE
Короче вот : http://prntscr.com/cdao0d

### ISSUE THREAD

**Issue by MAAATRIX2** [infinitystation/-tg-station#57]

**Comment by HetNeSS** [comment]
![http://prntscr.com/cdao0d](http://image.prntscr.com/image/7a14207735ce4a1d86cfb7de0a79cf97.png)

И.. Что тут?

**Comment by sir-duck** [comment]
Это зафикшено же еще давно, закрывайте

**Comment by ghost** [comment]
Закрыто, проблема давно решена.
