### ISSUE TITLE
Дополнительные места стыковки шаттла отбытия.

### ISSUE THREAD

**Issue by HetNeSS** [infinitystation/-tg-station#60]
Было бы здорово если б шаттл стыковался не в одно и то же место, а занимал доки прибытия, например. Если, конечно, они свободны. Тем самым усложнить задачу ряду трейторов и ИИ, взламывающих отбытие уже в начале смены. И оповещение в какой именно док произойдет стыковка примерно минут за пять до прибытия. И, по возможности, и разные шаттлы. Например, ту бандуру, которая стыкуется обычно в доках отбытия на 50+ человек можно заменить классическим ферри-шаттлом. И чтоб шаттл прибытия тоже не задерживался в доках. Или улетал при достижении половины отсчета о стыковке шаттла эвакуации.

**Comment by Terror4000rus** [comment]
:? 
Вообще, это возможно.
Но не второй шаттл - максимум заставить летать шаттл прибытия.
