### ISSUE TITLE
Звук голосования

### ISSUE THREAD

**Issue by Terror4000rus** [infinitystation/-tg-station#62]
Часто, при создании голосования, его видят исключительно игроки, что находятся в активной игре.
Мирно сидящий в баре ассистент, что просо существует не замечает голосования, будучи поглощенным иным занятием.
Я предлагаю добавить звук при создании голосования.

**Comment by Broda1** [comment]
Сделаю. _Может быть._

**Comment by sir-duck** [comment]
Выпиливайте issue, сделано.
