### ISSUE TITLE
Space Law пустой

### ISSUE THREAD

**Issue by vetwiz** [infinitystation/-tg-station#72]
В Space Law неверная ссылка, в результате при открытии книги видим вот это:
![image](https://cloud.githubusercontent.com/assets/1344537/19402900/4c2b9cf8-927d-11e6-8caf-d2e6c86f78b1.png)
Или ссылку почините или встройте законы в код книги отформатированные под внутриигровой стиль.

**Comment by T0rv** [comment]
#75 Починка должна быть тут, если вика опять заболеет книги опять перестанут работать.
