### ISSUE TITLE
Спавн ашвалкеров давным-давно сломан.

### ISSUE THREAD

**Issue by Ratvar** [infinitystation/-tg-station#84]
В половине случаев место спавна ашвалкеров перекрыто лавой,ведь кусок в центре не проработан.
Они даже выйти не могут никак часто,а так один-два-три выхода закрыты будут
http://imgur.com/a/3qz9J
Перемапить бы.

**Comment by ghost** [comment]
Если не ошибаюсь, уже зафиксешно.
